### PR TITLE
Add lints to check when an object store is required

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Description

[sc-70234]

### CODE REVIEW

**Review by emosbaugh — COMMENTED** [review]
Shouldn't this be added to kurlkinds linter rather than here? @ricardomaraschini 

https://github.com/replicatedhq/kurlkinds/blob/1d0d4f01322656b0a3de197512b313672c733fb8/pkg/lint/rego/output.rego

**Comment by ricardomaraschini** [comment]
> Shouldn't this be added to kurlkinds linter rather than here? @ricardomaraschini
> 
> https://github.com/replicatedhq/kurlkinds/blob/1d0d4f01322656b0a3de197512b313672c733fb8/pkg/lint/rego/output.rego

Yes, it should be added there for sure.

**Comment by emosbaugh** [comment]
> > Shouldn't this be added to kurlkinds linter rather than here? @ricardomaraschini
> > https://github.com/replicatedhq/kurlkinds/blob/1d0d4f01322656b0a3de197512b313672c733fb8/pkg/lint/rego/output.rego
> 
> Yes, it should be added there for sure.

@ricardomaraschini to be more specific, should this pr be closed or should we validate in both lint and api? i tend to think that we should no longer add validation in the api and instead prefer the linter.

**Comment by ricardomaraschini** [comment]
> > > Shouldn't this be added to kurlkinds linter rather than here? @ricardomaraschini
> > > https://github.com/replicatedhq/kurlkinds/blob/1d0d4f01322656b0a3de197512b313672c733fb8/pkg/lint/rego/output.rego
> > 
> > 
> > Yes, it should be added there for sure.
> 
> @ricardomaraschini to be more specific, should this pr be closed or should we validate in both lint and api? i tend to think that we should no longer add validation in the api and instead prefer the linter.

Now kurl.sh uses the linter so there is no need to add it on both. I would prefer to close this one and open one there. @camilamacedo86 do you need help with that ?

**Pull request closed without merging**
